#!/usr/bin/env perl
use Dzpl
    name => 'Net-ClientServer',
    version => '0.0006',
    author => 'Robert Krimen <robertkrimen@gmail.com>',
    license => 'Perl5',
    copyright => 'Robert Krimen',

    require => q/
        Any::Moose
        Path::Class
        Daemon::Daemonize
        File::HomeDir
        IO::Socket::INET

        [Test]
        Test::Most
    /,
;

{ plugin '@ROKR' }

